version: '3'
services:
# Miner 1
  miner1:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python main.py docker-configs/configForMiner1.json'
    ports: 
      - "50051:50051"
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.11'
# Miner 2
  miner2:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python main.py docker-configs/configForMiner2.json'
    ports: 
      - "50052:50052"
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.12'
# Miner 3
  miner3:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python main.py docker-configs/configForMiner3.json'
    ports: 
      - "50053:50053"
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.13'
# Miner 4
  miner4:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python main.py docker-configs/configForMiner4.json'
    ports: 
      - "50054:50054"
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.14'
# Miner 5
  miner5:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python main.py docker-configs/configForMiner5.json'
    ports: 
      - "50055:50055"
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.15'
# Viewer 1
  viewer1:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python ledgerViewer.py docker-configs/configForMiner1.json'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    depends_on: 
      - miner1
# Viewer 2
  viewer2:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python ledgerViewer.py docker-configs/configForMiner2.json'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
# Viewer 3
  viewer3:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python ledgerViewer.py docker-configs/configForMiner3.json'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
# Viewer 4
  viewer4:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python ledgerViewer.py docker-configs/configForMiner4.json'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
# Viewer 5
  viewer5:
    build: './blockchain'
    volumes: 
      - "./blockchain/docker-configs:/usr/src/blockchain-app/docker-configs"
    command: 'python ledgerViewer.py docker-configs/configForMiner5.json'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
# Client (NOT IN LISTEN MODE)
  client:
    build: './blockchain'
    command: 'python main.py docker-configs/configForClient.json e2 10'
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    networks:
      my-blockchain-network:
        ipv4_address: '1.0.0.20'
# Network
networks: 
  my-blockchain-network:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 1.0.0.0/24 
