# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BlockStoringInLedger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BlockStoringInLedger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x42lockStoringInLedger.proto\"\xb4\x01\n\x1b\x42lockStoringInLedgerRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\t\x12\x19\n\x11transactions_list\x18\x03 \x01(\t\x12\x12\n\nblock_hash\x18\x04 \x01(\t\x12\x16\n\x0elottery_number\x18\x05 \x01(\t\x12\x15\n\rminer_address\x18\x06 \x01(\t\x12\x1b\n\x13previous_block_hash\x18\x07 \x01(\t\"-\n\x1c\x42lockStoringInLedgerResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32{\n\x14\x42lockStoringInLedger\x12\x63\n$sendBlockStoringInLedgerNotification\x12\x1c.BlockStoringInLedgerRequest\x1a\x1d.BlockStoringInLedgerResponseb\x06proto3'
)




_BLOCKSTORINGINLEDGERREQUEST = _descriptor.Descriptor(
  name='BlockStoringInLedgerRequest',
  full_name='BlockStoringInLedgerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='BlockStoringInLedgerRequest.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seed', full_name='BlockStoringInLedgerRequest.seed', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions_list', full_name='BlockStoringInLedgerRequest.transactions_list', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block_hash', full_name='BlockStoringInLedgerRequest.block_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lottery_number', full_name='BlockStoringInLedgerRequest.lottery_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='miner_address', full_name='BlockStoringInLedgerRequest.miner_address', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_block_hash', full_name='BlockStoringInLedgerRequest.previous_block_hash', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=211,
)


_BLOCKSTORINGINLEDGERRESPONSE = _descriptor.Descriptor(
  name='BlockStoringInLedgerResponse',
  full_name='BlockStoringInLedgerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='BlockStoringInLedgerResponse.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=258,
)

DESCRIPTOR.message_types_by_name['BlockStoringInLedgerRequest'] = _BLOCKSTORINGINLEDGERREQUEST
DESCRIPTOR.message_types_by_name['BlockStoringInLedgerResponse'] = _BLOCKSTORINGINLEDGERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockStoringInLedgerRequest = _reflection.GeneratedProtocolMessageType('BlockStoringInLedgerRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKSTORINGINLEDGERREQUEST,
  '__module__' : 'BlockStoringInLedger_pb2'
  # @@protoc_insertion_point(class_scope:BlockStoringInLedgerRequest)
  })
_sym_db.RegisterMessage(BlockStoringInLedgerRequest)

BlockStoringInLedgerResponse = _reflection.GeneratedProtocolMessageType('BlockStoringInLedgerResponse', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKSTORINGINLEDGERRESPONSE,
  '__module__' : 'BlockStoringInLedger_pb2'
  # @@protoc_insertion_point(class_scope:BlockStoringInLedgerResponse)
  })
_sym_db.RegisterMessage(BlockStoringInLedgerResponse)



_BLOCKSTORINGINLEDGER = _descriptor.ServiceDescriptor(
  name='BlockStoringInLedger',
  full_name='BlockStoringInLedger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=260,
  serialized_end=383,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendBlockStoringInLedgerNotification',
    full_name='BlockStoringInLedger.sendBlockStoringInLedgerNotification',
    index=0,
    containing_service=None,
    input_type=_BLOCKSTORINGINLEDGERREQUEST,
    output_type=_BLOCKSTORINGINLEDGERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKSTORINGINLEDGER)

DESCRIPTOR.services_by_name['BlockStoringInLedger'] = _BLOCKSTORINGINLEDGER

# @@protoc_insertion_point(module_scope)
