# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comunication.grpc_protos.Transaction_pb2 as Transaction__pb2


class TransactionStub(object):
    """*
    Transaction service. It permit to sen transactions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendTransaction = channel.unary_unary(
                '/Transaction/sendTransaction',
                request_serializer=Transaction__pb2.TransactionRequest.SerializeToString,
                response_deserializer=Transaction__pb2.TransactionResponse.FromString,
                )


class TransactionServicer(object):
    """*
    Transaction service. It permit to sen transactions
    """

    def sendTransaction(self, request, context):
        """*
        Send transaction function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.sendTransaction,
                    request_deserializer=Transaction__pb2.TransactionRequest.FromString,
                    response_serializer=Transaction__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transaction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transaction(object):
    """*
    Transaction service. It permit to sen transactions
    """

    @staticmethod
    def sendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transaction/sendTransaction',
            Transaction__pb2.TransactionRequest.SerializeToString,
            Transaction__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
